/* eslint-disable no-restricted-globals */
// const a = {
//   defaultSettings: {
//     _core: {
//       default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//     },
//     classname: '.react-player',
//     classname_pause: '.close',
//     playerType: 'simple',
//     thumbnail: 0,
//     width: '100%',
//     height: '259px',
//     buttonText: 'Play Video',
//     autoplay: 0,
//     muted: 0,
//     controls: 1,
//     responsive: 0,
//     loop: 0,
//     previewPlayButton: 0,
//     audio: {
//       classname: '.react-audio-player',
//       classname_pause: '.close',
//       playerType: 'simple',
//       buttonText: 'Play Audio',
//       autoplay: 0,
//       muted: 0,
//       controls: 1,
//       loop: 0,
//     },
//     cookies: [
//       {
//         external_services: 'you.com',
//         categories: 'C0002, C0003',
//         message:
//           'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//         button: 'Allow cookies',
//       },
//     ],
//   },
//   videos_list: {
//     'video-embed-field-provider-9716-0': {
//       _core: {
//         default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//       },
//       classname: '.react-player',
//       classname_pause: '.close',
//       playerType: 'simple',
//       thumbnail: 0,
//       width: '100%',
//       height: '259px',
//       buttonText: 'Play Video',
//       autoplay: 0,
//       muted: 0,
//       controls: 1,
//       responsive: 0,
//       loop: 0,
//       previewPlayButton: 0,
//       audio: {
//         classname: '.react-audio-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         buttonText: 'Play Audio',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         loop: 0,
//       },
//       cookies: [
//         {
//           external_services: 'you.com',
//           categories: 'C0002, C0003',
//           message:
//             'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//           button: 'Allow cookies',
//         },
//       ],
//       url: 'https://vimeo.com/997605451',
//       playing: false,
//       playerSettings: {
//         _core: {
//           default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//         },
//         classname: '.react-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         thumbnail: 0,
//         width: '100%',
//         height: '259px',
//         buttonText: 'Play Video',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         responsive: 0,
//         loop: 0,
//         previewPlayButton: 0,
//         audio: {
//           classname: '.react-audio-player',
//           classname_pause: '.close',
//           playerType: 'simple',
//           buttonText: 'Play Audio',
//           autoplay: 0,
//           muted: 0,
//           controls: 1,
//           loop: 0,
//         },
//         cookies: [
//           {
//             external_services: 'you.com',
//             categories: 'C0002, C0003',
//             message:
//               'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//             button: 'Allow cookies',
//           },
//         ],
//       },
//       light: false,
//       displayThumbnail: 1,
//       displayVideo: 0,
//       id: 'video-embed-field-provider-9716-0',
//     },
//     'video-embed-field-provider-9681-0': {
//       _core: {
//         default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//       },
//       classname: '.react-player',
//       classname_pause: '.close',
//       playerType: 'simple',
//       thumbnail: 0,
//       width: '100%',
//       height: '259px',
//       buttonText: 'Play Video',
//       autoplay: 0,
//       muted: 0,
//       controls: 1,
//       responsive: 0,
//       loop: 0,
//       previewPlayButton: 0,
//       audio: {
//         classname: '.react-audio-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         buttonText: 'Play Audio',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         loop: 0,
//       },
//       cookies: [
//         {
//           external_services: 'you.com',
//           categories: 'C0002, C0003',
//           message:
//             'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//           button: 'Allow cookies',
//         },
//       ],
//       url: 'https://vimeo.com/997605560',
//       playing: false,
//       playerSettings: {
//         _core: {
//           default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//         },
//         classname: '.react-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         thumbnail: 0,
//         width: '100%',
//         height: '259px',
//         buttonText: 'Play Video',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         responsive: 0,
//         loop: 0,
//         previewPlayButton: 0,
//         audio: {
//           classname: '.react-audio-player',
//           classname_pause: '.close',
//           playerType: 'simple',
//           buttonText: 'Play Audio',
//           autoplay: 0,
//           muted: 0,
//           controls: 1,
//           loop: 0,
//         },
//         cookies: [
//           {
//             external_services: 'you.com',
//             categories: 'C0002, C0003',
//             message:
//               'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//             button: 'Allow cookies',
//           },
//         ],
//       },
//       light: false,
//       displayThumbnail: 1,
//       displayVideo: 0,
//       id: 'video-embed-field-provider-9681-0',
//     },
//     'video-embed-field-provider-9646-0': {
//       _core: {
//         default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//       },
//       classname: '.react-player',
//       classname_pause: '.close',
//       playerType: 'simple',
//       thumbnail: 0,
//       width: '100%',
//       height: '259px',
//       buttonText: 'Play Video',
//       autoplay: 0,
//       muted: 0,
//       controls: 1,
//       responsive: 0,
//       loop: 0,
//       previewPlayButton: 0,
//       audio: {
//         classname: '.react-audio-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         buttonText: 'Play Audio',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         loop: 0,
//       },
//       cookies: [
//         {
//           external_services: 'you.com',
//           categories: 'C0002, C0003',
//           message:
//             'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//           button: 'Allow cookies',
//         },
//       ],
//       url: 'https://vimeo.com/997605573',
//       playing: false,
//       playerSettings: {
//         _core: {
//           default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//         },
//         classname: '.react-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         thumbnail: 0,
//         width: '100%',
//         height: '259px',
//         buttonText: 'Play Video',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         responsive: 0,
//         loop: 0,
//         previewPlayButton: 0,
//         audio: {
//           classname: '.react-audio-player',
//           classname_pause: '.close',
//           playerType: 'simple',
//           buttonText: 'Play Audio',
//           autoplay: 0,
//           muted: 0,
//           controls: 1,
//           loop: 0,
//         },
//         cookies: [
//           {
//             external_services: 'you.com',
//             categories: 'C0002, C0003',
//             message:
//               'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//             button: 'Allow cookies',
//           },
//         ],
//       },
//       light: false,
//       displayThumbnail: 1,
//       displayVideo: 0,
//       id: 'video-embed-field-provider-9646-0',
//     },
//     'video-embed-field-provider-9611-0': {
//       _core: {
//         default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//       },
//       classname: '.react-player',
//       classname_pause: '.close',
//       playerType: 'simple',
//       thumbnail: 0,
//       width: '100%',
//       height: '259px',
//       buttonText: 'Play Video',
//       autoplay: 0,
//       muted: 0,
//       controls: 1,
//       responsive: 0,
//       loop: 0,
//       previewPlayButton: 0,
//       audio: {
//         classname: '.react-audio-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         buttonText: 'Play Audio',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         loop: 0,
//       },
//       cookies: [
//         {
//           external_services: 'you.com',
//           categories: 'C0002, C0003',
//           message:
//             'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//           button: 'Allow cookies',
//         },
//       ],
//       url: 'https://vimeo.com/997605503',
//       playing: false,
//       playerSettings: {
//         _core: {
//           default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//         },
//         classname: '.react-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         thumbnail: 0,
//         width: '100%',
//         height: '259px',
//         buttonText: 'Play Video',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         responsive: 0,
//         loop: 0,
//         previewPlayButton: 0,
//         audio: {
//           classname: '.react-audio-player',
//           classname_pause: '.close',
//           playerType: 'simple',
//           buttonText: 'Play Audio',
//           autoplay: 0,
//           muted: 0,
//           controls: 1,
//           loop: 0,
//         },
//         cookies: [
//           {
//             external_services: 'you.com',
//             categories: 'C0002, C0003',
//             message:
//               'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//             button: 'Allow cookies',
//           },
//         ],
//       },
//       light: false,
//       displayThumbnail: 1,
//       displayVideo: 0,
//       id: 'video-embed-field-provider-9611-0',
//     },
//     'video-embed-field-provider-9571-0': {
//       _core: {
//         default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//       },
//       classname: '.react-player',
//       classname_pause: '.close',
//       playerType: 'simple',
//       thumbnail: 0,
//       width: '100%',
//       height: '259px',
//       buttonText: 'Play Video',
//       autoplay: 0,
//       muted: 0,
//       controls: 1,
//       responsive: 0,
//       loop: 0,
//       previewPlayButton: 0,
//       audio: {
//         classname: '.react-audio-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         buttonText: 'Play Audio',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         loop: 0,
//       },
//       cookies: [
//         {
//           external_services: 'you.com',
//           categories: 'C0002, C0003',
//           message:
//             'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//           button: 'Allow cookies',
//         },
//       ],
//       url: 'https://vimeo.com/997605613',
//       playing: false,
//       playerSettings: {
//         _core: {
//           default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//         },
//         classname: '.react-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         thumbnail: 0,
//         width: '100%',
//         height: '259px',
//         buttonText: 'Play Video',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         responsive: 0,
//         loop: 0,
//         previewPlayButton: 0,
//         audio: {
//           classname: '.react-audio-player',
//           classname_pause: '.close',
//           playerType: 'simple',
//           buttonText: 'Play Audio',
//           autoplay: 0,
//           muted: 0,
//           controls: 1,
//           loop: 0,
//         },
//         cookies: [
//           {
//             external_services: 'you.com',
//             categories: 'C0002, C0003',
//             message:
//               'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//             button: 'Allow cookies',
//           },
//         ],
//       },
//       light: false,
//       displayThumbnail: 1,
//       displayVideo: 0,
//       id: 'video-embed-field-provider-9571-0',
//     },
//     'video-embed-field-provider-9786-0': {
//       _core: {
//         default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//       },
//       classname: '.react-player',
//       classname_pause: '.close',
//       playerType: 'simple',
//       thumbnail: 0,
//       width: '100%',
//       height: '259px',
//       buttonText: 'Play Video',
//       autoplay: 0,
//       muted: 0,
//       controls: 1,
//       responsive: 0,
//       loop: 0,
//       previewPlayButton: 0,
//       audio: {
//         classname: '.react-audio-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         buttonText: 'Play Audio',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         loop: 0,
//       },
//       cookies: [
//         {
//           external_services: 'you.com',
//           categories: 'C0002, C0003',
//           message:
//             'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//           button: 'Allow cookies',
//         },
//       ],
//       url: 'https://vimeo.com/997605389',
//       playing: false,
//       playerSettings: {
//         _core: {
//           default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//         },
//         classname: '.react-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         thumbnail: 0,
//         width: '100%',
//         height: '259px',
//         buttonText: 'Play Video',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         responsive: 0,
//         loop: 0,
//         previewPlayButton: 0,
//         audio: {
//           classname: '.react-audio-player',
//           classname_pause: '.close',
//           playerType: 'simple',
//           buttonText: 'Play Audio',
//           autoplay: 0,
//           muted: 0,
//           controls: 1,
//           loop: 0,
//         },
//         cookies: [
//           {
//             external_services: 'you.com',
//             categories: 'C0002, C0003',
//             message:
//               'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//             button: 'Allow cookies',
//           },
//         ],
//       },
//       light: false,
//       displayThumbnail: 1,
//       displayVideo: 0,
//       id: 'video-embed-field-provider-9786-0',
//     },
//     'video-embed-field-provider-12416-0': {
//       _core: {
//         default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//       },
//       classname: '.react-player',
//       classname_pause: '.close',
//       playerType: 'simple',
//       thumbnail: 0,
//       width: '100%',
//       height: '259px',
//       buttonText: 'Play Video',
//       autoplay: 0,
//       muted: 0,
//       controls: 1,
//       responsive: 0,
//       loop: 0,
//       previewPlayButton: 0,
//       audio: {
//         classname: '.react-audio-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         buttonText: 'Play Audio',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         loop: 0,
//       },
//       cookies: [
//         {
//           external_services: 'you.com',
//           categories: 'C0002, C0003',
//           message:
//             'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//           button: 'Allow cookies',
//         },
//       ],
//       url: 'https://vimeo.com/1069561885',
//       playing: false,
//       playerSettings: {
//         _core: {
//           default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//         },
//         classname: '.react-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         thumbnail: 0,
//         width: '100%',
//         height: '259px',
//         buttonText: 'Play Video',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         responsive: 0,
//         loop: 0,
//         previewPlayButton: 0,
//         audio: {
//           classname: '.react-audio-player',
//           classname_pause: '.close',
//           playerType: 'simple',
//           buttonText: 'Play Audio',
//           autoplay: 0,
//           muted: 0,
//           controls: 1,
//           loop: 0,
//         },
//         cookies: [
//           {
//             external_services: 'you.com',
//             categories: 'C0002, C0003',
//             message:
//               'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//             button: 'Allow cookies',
//           },
//         ],
//       },
//       light: false,
//       displayThumbnail: 1,
//       displayVideo: 0,
//       id: 'video-embed-field-provider-12416-0',
//     },
//     'video-embed-field-provider-12381-0': {
//       _core: {
//         default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//       },
//       classname: '.react-player',
//       classname_pause: '.close',
//       playerType: 'simple',
//       thumbnail: 0,
//       width: '100%',
//       height: '259px',
//       buttonText: 'Play Video',
//       autoplay: 0,
//       muted: 0,
//       controls: 1,
//       responsive: 0,
//       loop: 0,
//       previewPlayButton: 0,
//       audio: {
//         classname: '.react-audio-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         buttonText: 'Play Audio',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         loop: 0,
//       },
//       cookies: [
//         {
//           external_services: 'you.com',
//           categories: 'C0002, C0003',
//           message:
//             'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//           button: 'Allow cookies',
//         },
//       ],
//       url: 'https://vimeo.com/1069561634',
//       playing: false,
//       playerSettings: {
//         _core: {
//           default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//         },
//         classname: '.react-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         thumbnail: 0,
//         width: '100%',
//         height: '259px',
//         buttonText: 'Play Video',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         responsive: 0,
//         loop: 0,
//         previewPlayButton: 0,
//         audio: {
//           classname: '.react-audio-player',
//           classname_pause: '.close',
//           playerType: 'simple',
//           buttonText: 'Play Audio',
//           autoplay: 0,
//           muted: 0,
//           controls: 1,
//           loop: 0,
//         },
//         cookies: [
//           {
//             external_services: 'you.com',
//             categories: 'C0002, C0003',
//             message:
//               'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//             button: 'Allow cookies',
//           },
//         ],
//       },
//       light: false,
//       displayThumbnail: 1,
//       displayVideo: 0,
//       id: 'video-embed-field-provider-12381-0',
//     },
//     'video-embed-field-provider-9751-0': {
//       _core: {
//         default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//       },
//       classname: '.react-player',
//       classname_pause: '.close',
//       playerType: 'simple',
//       thumbnail: 0,
//       width: '100%',
//       height: '259px',
//       buttonText: 'Play Video',
//       autoplay: 0,
//       muted: 0,
//       controls: 1,
//       responsive: 0,
//       loop: 0,
//       previewPlayButton: 0,
//       audio: {
//         classname: '.react-audio-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         buttonText: 'Play Audio',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         loop: 0,
//       },
//       cookies: [
//         {
//           external_services: 'you.com',
//           categories: 'C0002, C0003',
//           message:
//             'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//           button: 'Allow cookies',
//         },
//       ],
//       url: 'https://vimeo.com/997605068',
//       playing: false,
//       playerSettings: {
//         _core: {
//           default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//         },
//         classname: '.react-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         thumbnail: 0,
//         width: '100%',
//         height: '259px',
//         buttonText: 'Play Video',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         responsive: 0,
//         loop: 0,
//         previewPlayButton: 0,
//         audio: {
//           classname: '.react-audio-player',
//           classname_pause: '.close',
//           playerType: 'simple',
//           buttonText: 'Play Audio',
//           autoplay: 0,
//           muted: 0,
//           controls: 1,
//           loop: 0,
//         },
//         cookies: [
//           {
//             external_services: 'you.com',
//             categories: 'C0002, C0003',
//             message:
//               'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//             button: 'Allow cookies',
//           },
//         ],
//       },
//       light: false,
//       displayThumbnail: 1,
//       displayVideo: 0,
//       id: 'video-embed-field-provider-9751-0',
//     },
//     'video-embed-field-provider-12346-0': {
//       _core: {
//         default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//       },
//       classname: '.react-player',
//       classname_pause: '.close',
//       playerType: 'simple',
//       thumbnail: 0,
//       width: '100%',
//       height: '259px',
//       buttonText: 'Play Video',
//       autoplay: 0,
//       muted: 0,
//       controls: 1,
//       responsive: 0,
//       loop: 0,
//       previewPlayButton: 0,
//       audio: {
//         classname: '.react-audio-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         buttonText: 'Play Audio',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         loop: 0,
//       },
//       cookies: [
//         {
//           external_services: 'you.com',
//           categories: 'C0002, C0003',
//           message:
//             'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//           button: 'Allow cookies',
//         },
//       ],
//       url: 'https://vimeo.com/1069552294',
//       playing: false,
//       playerSettings: {
//         _core: {
//           default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//         },
//         classname: '.react-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         thumbnail: 0,
//         width: '100%',
//         height: '259px',
//         buttonText: 'Play Video',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         responsive: 0,
//         loop: 0,
//         previewPlayButton: 0,
//         audio: {
//           classname: '.react-audio-player',
//           classname_pause: '.close',
//           playerType: 'simple',
//           buttonText: 'Play Audio',
//           autoplay: 0,
//           muted: 0,
//           controls: 1,
//           loop: 0,
//         },
//         cookies: [
//           {
//             external_services: 'you.com',
//             categories: 'C0002, C0003',
//             message:
//               'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//             button: 'Allow cookies',
//           },
//         ],
//       },
//       light: false,
//       displayThumbnail: 1,
//       displayVideo: 0,
//       id: 'video-embed-field-provider-12346-0',
//     },
//     'video-embed-field-provider-12311-0': {
//       _core: {
//         default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//       },
//       classname: '.react-player',
//       classname_pause: '.close',
//       playerType: 'simple',
//       thumbnail: 0,
//       width: '100%',
//       height: '259px',
//       buttonText: 'Play Video',
//       autoplay: 0,
//       muted: 0,
//       controls: 1,
//       responsive: 0,
//       loop: 0,
//       previewPlayButton: 0,
//       audio: {
//         classname: '.react-audio-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         buttonText: 'Play Audio',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         loop: 0,
//       },
//       cookies: [
//         {
//           external_services: 'you.com',
//           categories: 'C0002, C0003',
//           message:
//             'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//           button: 'Allow cookies',
//         },
//       ],
//       url: 'https://vimeo.com/1069560258',
//       playing: false,
//       playerSettings: {
//         _core: {
//           default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//         },
//         classname: '.react-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         thumbnail: 0,
//         width: '100%',
//         height: '259px',
//         buttonText: 'Play Video',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         responsive: 0,
//         loop: 0,
//         previewPlayButton: 0,
//         audio: {
//           classname: '.react-audio-player',
//           classname_pause: '.close',
//           playerType: 'simple',
//           buttonText: 'Play Audio',
//           autoplay: 0,
//           muted: 0,
//           controls: 1,
//           loop: 0,
//         },
//         cookies: [
//           {
//             external_services: 'you.com',
//             categories: 'C0002, C0003',
//             message:
//               'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//             button: 'Allow cookies',
//           },
//         ],
//       },
//       light: false,
//       displayThumbnail: 1,
//       displayVideo: 0,
//       id: 'video-embed-field-provider-12311-0',
//     },
//     'video-embed-field-provider-12571-0': {
//       playerType: 'simple',
//       buttonText: 'Play Video',
//       autoplay: '1',
//       controls: '1',
//       thumbnail: 0,
//       muted: 0,
//       loop: 0,
//       responsive: 0,
//       previewPlayButton: 0,
//       _core: {
//         default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//       },
//       classname: '.react-player',
//       classname_pause: '.close',
//       width: '100%',
//       height: '259px',
//       audio: {
//         classname: '.react-audio-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         buttonText: 'Play Audio',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         loop: 0,
//       },
//       cookies: [
//         {
//           external_services: 'you.com',
//           categories: 'C0002, C0003',
//           message:
//             'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//           button: 'Allow cookies',
//         },
//       ],
//       url: 'https://vimeo.com/1093977581',
//       playing: true,
//       playerSettings: {
//         playerType: 'simple',
//         buttonText: 'Play Video',
//         autoplay: '1',
//         controls: '1',
//         thumbnail: 0,
//         muted: 0,
//         loop: 0,
//         responsive: 0,
//         previewPlayButton: 0,
//         _core: {
//           default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//         },
//         classname: '.react-player',
//         classname_pause: '.close',
//         width: '100%',
//         height: '259px',
//         audio: {
//           classname: '.react-audio-player',
//           classname_pause: '.close',
//           playerType: 'simple',
//           buttonText: 'Play Audio',
//           autoplay: 0,
//           muted: 0,
//           controls: 1,
//           loop: 0,
//         },
//         cookies: [
//           {
//             external_services: 'you.com',
//             categories: 'C0002, C0003',
//             message:
//               'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//             button: 'Allow cookies',
//           },
//         ],
//       },
//       light: false,
//       displayThumbnail: 1,
//       displayVideo: 0,
//       id: 'video-embed-field-provider-12571-0',
//     },
//     'video-embed-field-provider-9521-0': {
//       playerType: 'simple',
//       buttonText: 'Play Video',
//       autoplay: '1',
//       controls: '1',
//       thumbnail: 0,
//       muted: 0,
//       loop: 0,
//       responsive: 0,
//       previewPlayButton: 0,
//       _core: {
//         default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//       },
//       classname: '.react-player',
//       classname_pause: '.close',
//       width: '100%',
//       height: '259px',
//       audio: {
//         classname: '.react-audio-player',
//         classname_pause: '.close',
//         playerType: 'simple',
//         buttonText: 'Play Audio',
//         autoplay: 0,
//         muted: 0,
//         controls: 1,
//         loop: 0,
//       },
//       cookies: [
//         {
//           external_services: 'you.com',
//           categories: 'C0002, C0003',
//           message:
//             'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//           button: 'Allow cookies',
//         },
//       ],
//       url: 'https://vimeo.com/1080076492',
//       playing: true,
//       playerSettings: {
//         playerType: 'simple',
//         buttonText: 'Play Video',
//         autoplay: '1',
//         controls: '1',
//         thumbnail: 0,
//         muted: 0,
//         loop: 0,
//         responsive: 0,
//         previewPlayButton: 0,
//         _core: {
//           default_config_hash: 'SU-S-KRefsnb4PVlEUcyJVbMGQgY__QpXVyw85V3dRs',
//         },
//         classname: '.react-player',
//         classname_pause: '.close',
//         width: '100%',
//         height: '259px',
//         audio: {
//           classname: '.react-audio-player',
//           classname_pause: '.close',
//           playerType: 'simple',
//           buttonText: 'Play Audio',
//           autoplay: 0,
//           muted: 0,
//           controls: 1,
//           loop: 0,
//         },
//         cookies: [
//           {
//             external_services: 'you.com',
//             categories: 'C0002, C0003',
//             message:
//               'You can\u0027t play the video.\u003Cbr /\u003EPlease apply Functional and Analytics cookies.',
//             button: 'Allow cookies',
//           },
//         ],
//       },
//       light:
//         '/sites/g/files/qhldwo11071/files/2025-05/caregiving-thumbnail.jpeg',
//       displayThumbnail: 1,
//       displayVideo: 0,
//       id: 'video-embed-field-provider-9521-0',
//     },
//   },
// };

export default function decorate(block) {
  const videoURL = block.children[0]?.textContent?.trim();
  if (videoURL) {
    const htmlVideoElement = document.createElement('div');
    htmlVideoElement.setAttribute('data-vimeo-url', videoURL);
    // htmlVideoElement.setAttribute('data-vimeo-width', '457');
    // htmlVideoElement.setAttribute('data-vimeo-height', '259px');
    htmlVideoElement.setAttribute('id', 'video-1');

    block.append(htmlVideoElement);

    addEventListener('DOMContentLoaded', () => {
      const videoContainer = document.querySelector('#video-1');
      // eslint-disable-next-line no-undef
      const player = new Vimeo.Player(videoContainer);

      player.on('play', () => {
        console.log('Played the video');
      });
    });
  }
}
